### ISSUE TITLE
Request: standalone references?

### ISSUE THREAD

**Issue by assyrianic** [compuphase/pawn#30]
Is it alright that I request Pawn to have standalone references like C++ does?
```c++
new i = 5;
new &p = i;
p = 9; // i is now 9
```

Perhaps denote it by giving it a different operator?
modified example above
```c++
new i = 5;
new @p = i;
p = 9; // i is now 9
```

Same example above but with floating point.
```c++
new float:f = 5.02;
new &float:p = f;
p = 3.14; // f is now 3.14
```

**Comment by Y-Less** [comment]
The `@p` example won't work - `@` is already a valid symbol character in PAWN (though rarely used outside of low-level libraries), so `@p` is a valid variable now.  Also, a function with `@` as the first character of its name is public even without the `public` keyword:

```pawn
@MyPublic();

@MyPublic()
{
    print("hi");
}

main()
{
    CallLocalFunction("@MyPublic", ""); // Works.
}
```

Note that this is not quite a replacement for `public` because it remains part of the name, you can't do `@ MyPublic` and then just refer to the function as `MyPublic`.

The `&` operator on the other hand already has precedence for this in that it is the syntax when declaring functions, so a different syntax would probably be more confusing.  (Side note, I also used `&` for some libraries that can take the address of a function in the same way).

**Comment by assyrianic** [comment]
hmmm, how about `$` for standalone references?
Example:
```c++
new i = 5;
new $p = i;
p = 2; // i == 2
```
I don't believe the $ is used is it?

**Comment by Y-Less** [comment]
No, but still why not just `&` - I think that would cause far less confusion as it already means that:

```pawn
MyFunc(&a, &b)
{
    a = 7;
    printf("%d", b); // Prints 7.
}

main()
{
    new var = 11;
    MyFunc(var, var);
}
```
