### ISSUE TITLE
Empty body main generates wrong output

### ISSUE THREAD

**Issue by namazso** [compuphase/pawn#78]
The following code:
```
main()
    ;
```

generates the following output:
```
HALT 0
```

with main pointing at 2, so end of file. There is no RET or RETN

**Comment by compuphase** [comment]
If that code is built with default options, you will get warning 218 "old style prototypes used with optional semicolon". This hints at what is wrong: the line is seen as a C-style function prototype, not as a function implementation. So the script has a prototype for main, but not an implementation. Which is why no code is generated.

The "empty statement" in Pawn is {} (open and close curly braces). A semicolon is not an empty statement.

Though, there problems in the Pawn compiler laid bare by this issue:

1) If you build with the "-;" option (semicolons are *not* optional), there is no warning at all (and no generated code).

2) The compiler is supposed to signal the error that a script has no entry point (either "main" or any public function).

Commit eeca7935f6205833e196aef767aaa0243abeba97 has a fix for the second point.
